included:
    - ./
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
cyclomatic_complexity:
    warning: 20
    error: 30
function_body_length:
    warning: 75
    error: 100
file_length:
    warning: 500
    error: 600
type_body_length:
    warning: 300
    error: 400
identifier_name:
    excluded: id # id is allowed
